### ISSUE TITLE
Set CSS in index.html zoom 90%

### ISSUE THREAD

**Issue by Longwater1234** [Longwater1234/WedemyClient#118]
Make sure you set zoom: 0.9 in index.html, also only for width > 1280px screen
```css
html {
 zoom: 0.9;
}
```
